/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.edu.pku.ss.matchmaker.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class PECRModel implements org.apache.thrift.TBase<PECRModel, PECRModel._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PECRModel");

  private static final org.apache.thrift.protocol.TField URI_FIELD_DESC = new org.apache.thrift.protocol.TField("URI", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField EXPRESSION_BODY_FIELD_DESC = new org.apache.thrift.protocol.TField("expressionBody", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PECRModelStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PECRModelTupleSchemeFactory());
  }

  public String URI; // optional
  public String expressionBody; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    URI((short)1, "URI"),
    EXPRESSION_BODY((short)2, "expressionBody");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // URI
          return URI;
        case 2: // EXPRESSION_BODY
          return EXPRESSION_BODY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.URI,_Fields.EXPRESSION_BODY};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.URI, new org.apache.thrift.meta_data.FieldMetaData("URI", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EXPRESSION_BODY, new org.apache.thrift.meta_data.FieldMetaData("expressionBody", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PECRModel.class, metaDataMap);
  }

  public PECRModel() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PECRModel(PECRModel other) {
    if (other.isSetURI()) {
      this.URI = other.URI;
    }
    if (other.isSetExpressionBody()) {
      this.expressionBody = other.expressionBody;
    }
  }

  public PECRModel deepCopy() {
    return new PECRModel(this);
  }

  @Override
  public void clear() {
    this.URI = null;
    this.expressionBody = null;
  }

  public String getURI() {
    return this.URI;
  }

  public PECRModel setURI(String URI) {
    this.URI = URI;
    return this;
  }

  public void unsetURI() {
    this.URI = null;
  }

  /** Returns true if field URI is set (has been assigned a value) and false otherwise */
  public boolean isSetURI() {
    return this.URI != null;
  }

  public void setURIIsSet(boolean value) {
    if (!value) {
      this.URI = null;
    }
  }

  public String getExpressionBody() {
    return this.expressionBody;
  }

  public PECRModel setExpressionBody(String expressionBody) {
    this.expressionBody = expressionBody;
    return this;
  }

  public void unsetExpressionBody() {
    this.expressionBody = null;
  }

  /** Returns true if field expressionBody is set (has been assigned a value) and false otherwise */
  public boolean isSetExpressionBody() {
    return this.expressionBody != null;
  }

  public void setExpressionBodyIsSet(boolean value) {
    if (!value) {
      this.expressionBody = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case URI:
      if (value == null) {
        unsetURI();
      } else {
        setURI((String)value);
      }
      break;

    case EXPRESSION_BODY:
      if (value == null) {
        unsetExpressionBody();
      } else {
        setExpressionBody((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case URI:
      return getURI();

    case EXPRESSION_BODY:
      return getExpressionBody();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case URI:
      return isSetURI();
    case EXPRESSION_BODY:
      return isSetExpressionBody();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PECRModel)
      return this.equals((PECRModel)that);
    return false;
  }

  public boolean equals(PECRModel that) {
    if (that == null)
      return false;

    boolean this_present_URI = true && this.isSetURI();
    boolean that_present_URI = true && that.isSetURI();
    if (this_present_URI || that_present_URI) {
      if (!(this_present_URI && that_present_URI))
        return false;
      if (!this.URI.equals(that.URI))
        return false;
    }

    boolean this_present_expressionBody = true && this.isSetExpressionBody();
    boolean that_present_expressionBody = true && that.isSetExpressionBody();
    if (this_present_expressionBody || that_present_expressionBody) {
      if (!(this_present_expressionBody && that_present_expressionBody))
        return false;
      if (!this.expressionBody.equals(that.expressionBody))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(PECRModel other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    PECRModel typedOther = (PECRModel)other;

    lastComparison = Boolean.valueOf(isSetURI()).compareTo(typedOther.isSetURI());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetURI()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.URI, typedOther.URI);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetExpressionBody()).compareTo(typedOther.isSetExpressionBody());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExpressionBody()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.expressionBody, typedOther.expressionBody);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PECRModel(");
    boolean first = true;

    if (isSetURI()) {
      sb.append("URI:");
      if (this.URI == null) {
        sb.append("null");
      } else {
        sb.append(this.URI);
      }
      first = false;
    }
    if (isSetExpressionBody()) {
      if (!first) sb.append(", ");
      sb.append("expressionBody:");
      if (this.expressionBody == null) {
        sb.append("null");
      } else {
        sb.append(this.expressionBody);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PECRModelStandardSchemeFactory implements SchemeFactory {
    public PECRModelStandardScheme getScheme() {
      return new PECRModelStandardScheme();
    }
  }

  private static class PECRModelStandardScheme extends StandardScheme<PECRModel> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PECRModel struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // URI
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.URI = iprot.readString();
              struct.setURIIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // EXPRESSION_BODY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.expressionBody = iprot.readString();
              struct.setExpressionBodyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PECRModel struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.URI != null) {
        if (struct.isSetURI()) {
          oprot.writeFieldBegin(URI_FIELD_DESC);
          oprot.writeString(struct.URI);
          oprot.writeFieldEnd();
        }
      }
      if (struct.expressionBody != null) {
        if (struct.isSetExpressionBody()) {
          oprot.writeFieldBegin(EXPRESSION_BODY_FIELD_DESC);
          oprot.writeString(struct.expressionBody);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PECRModelTupleSchemeFactory implements SchemeFactory {
    public PECRModelTupleScheme getScheme() {
      return new PECRModelTupleScheme();
    }
  }

  private static class PECRModelTupleScheme extends TupleScheme<PECRModel> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PECRModel struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetURI()) {
        optionals.set(0);
      }
      if (struct.isSetExpressionBody()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetURI()) {
        oprot.writeString(struct.URI);
      }
      if (struct.isSetExpressionBody()) {
        oprot.writeString(struct.expressionBody);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PECRModel struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.URI = iprot.readString();
        struct.setURIIsSet(true);
      }
      if (incoming.get(1)) {
        struct.expressionBody = iprot.readString();
        struct.setExpressionBodyIsSet(true);
      }
    }
  }

}

